### ISSUE TITLE
BackUp override/delete the wrong Folder

### ISSUE THREAD

**Issue by RzR32** [RzR32/Discord_Bot-RzR32_Bot#15]
![image](https://user-images.githubusercontent.com/46526880/72094186-20c06c00-3316-11ea-8e70-e133ab3f4658.png)

**Comment by johanneslosch** [comment]
I’m not sure what you want to say with this picture at this issue, because a description is missing

**Comment by RzR32** [comment]
Should be the last 7 days ...
So need to check the oldest created folder. (to delete)
(Hour.Minute.Second_Day.Month.Year)

**Comment by johanneslosch** [comment]
Oh okay, This may makes sense

I think that there is an opportunity to improve the saving. I create a new issue for this.
