### ISSUE TITLE
Improve backup folder

### ISSUE THREAD

**Issue by johanneslosch** [RzR32/Discord_Bot-RzR32_Bot#16]
Like I said in a comment at issue #15

I would the naming of the folders structure like 

**YYYY-MM-DD_HH-MM-SS**

But am not sure yet if seconds are needed because I don’t know the code behind it.

Also would it probably interesting the old backups in a .zip file for probably older logs.

**Comment by johanneslosch** [comment]
Since the code in BackUp.java is known to me now,

```

public class BackUp {

    LogBack LB = new LogBack();

    private SimpleDateFormat SDF = new SimpleDateFormat("HH.mm.ss_dd.MM.yy");
    private Date D = new Date();
    private String date = SDF.format(D);
    private File backup = new File("backup/");
    private File output = new File("backup/" + date + "/");
    private File input = new File("config/");

```
I am able to say that in my opinion the seconds are not needed.
It would improve the naming for other users.

That means I would prefer the naming 
**YYYY-MM-DD_HH-mm**
This is better searchable for a new user if there was a New Year’s Eve or a new month started.

**Comment by RzR32** [comment]
IDEA: Make a better structure in the .zip (for older backup´s)

- January
   > Backup 1
   > Backup 2
   > Backup 3
   > ...
- February
   > Backup 1
   > Backup 2
   > Backup 3
   > ...
- March
   > Backup 1
   > Backup 2
   > Backup 3
   > ...
- ...
