### ISSUE TITLE
Bug with NameChange.java

### ISSUE THREAD

**Issue by RzR32** [RzR32/Discord_Bot-RzR32_Bot#2]
> onUserUpdateName event

**Comment by K-EY** [comment]
I just wondering if this issue is with https://github.com/RzR32/Discord_Bot-RzR32_Bot/commit/c9fd4f0a98806da3e52e5782ed4ba7f7c08fcb45 done and closeable

**Comment by johanneslosch** [comment]
So after checking your code this issue should be closeable
